import type { Party, Product, PurchaseOrder } from "./types";

// ─── Parties ──────────────────────────────────────────────────────────────────

export const MOCK_PARTIES: Party[] = [
  {
    id: "party-001",
    name: "Alpha Textiles Pvt Ltd",
    phone: "+91 98765 43210",
    email: "orders@alphatextiles.in",
    gst: "27AABCA1234A1Z5",
    contactPerson: "Ramesh Kapoor",
    address: "45, MIDC Industrial Area, Pune – 411018",
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "party-002",
    name: "Sunrise Garments",
    phone: "+91 87654 32109",
    email: "info@sunrisegarments.com",
    gst: "29AABCS5678A1Z2",
    contactPerson: "Priya Mehta",
    address: "12, Commercial Street, Bengaluru – 560001",
    createdAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "party-003",
    name: "Metro Wholesale Suppliers",
    phone: "+91 76543 21098",
    contactPerson: "Anil Sharma",
    address: "88, Nehru Place, New Delhi – 110019",
    createdAt: "2024-03-05T09:30:00Z",
  },
  {
    id: "party-004",
    name: "FastTrack Logistics & Trade",
    email: "trade@fasttrack.co.in",
    gst: "06AABCF9012B1Z9",
    address: "Plot 7, Sector 32, Gurugram – 122001",
    createdAt: "2024-04-10T14:00:00Z",
  },
  {
    id: "party-005",
    name: "Kumar Brothers",
    phone: "+91 99887 76655",
    email: "kumarbrothers@gmail.com",
    createdAt: "2024-05-01T11:00:00Z",
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    name: "Classic Cotton T-Shirt",
    imageUrl: "https://placehold.co/60x60/e2e8f0/94a3b8?text=TS",
    category: "Tops",
    variants: [
      {
        id: "var-001-s-blk",
        sku: "TS-S-BLK",
        name: "S / Black",
        color: "Black",
        size: "S",
        currentBuyPrice: 180,
        currentStock: 45,
      },
      {
        id: "var-001-m-blk",
        sku: "TS-M-BLK",
        name: "M / Black",
        color: "Black",
        size: "M",
        currentBuyPrice: 180,
        currentStock: 60,
      },
      {
        id: "var-001-l-blk",
        sku: "TS-L-BLK",
        name: "L / Black",
        color: "Black",
        size: "L",
        currentBuyPrice: 185,
        currentStock: 30,
      },
      {
        id: "var-001-s-wht",
        sku: "TS-S-WHT",
        name: "S / White",
        color: "White",
        size: "S",
        currentBuyPrice: 175,
        currentStock: 55,
      },
      {
        id: "var-001-m-wht",
        sku: "TS-M-WHT",
        name: "M / White",
        color: "White",
        size: "M",
        currentBuyPrice: 175,
        currentStock: 80,
      },
      {
        id: "var-001-l-wht",
        sku: "TS-L-WHT",
        name: "L / White",
        color: "White",
        size: "L",
        currentBuyPrice: 180,
        currentStock: 20,
      },
    ],
  },
  {
    id: "prod-002",
    name: "Slim Fit Chinos",
    imageUrl: "https://placehold.co/60x60/ddd6fe/7c3aed?text=CH",
    category: "Bottoms",
    variants: [
      {
        id: "var-002-30-nvy",
        sku: "CH-30-NVY",
        name: "30 / Navy",
        color: "Navy",
        size: "30",
        currentBuyPrice: 420,
        currentStock: 25,
      },
      {
        id: "var-002-32-nvy",
        sku: "CH-32-NVY",
        name: "32 / Navy",
        color: "Navy",
        size: "32",
        currentBuyPrice: 420,
        currentStock: 35,
      },
      {
        id: "var-002-34-nvy",
        sku: "CH-34-NVY",
        name: "34 / Navy",
        color: "Navy",
        size: "34",
        currentBuyPrice: 425,
        currentStock: 18,
      },
      {
        id: "var-002-32-khk",
        sku: "CH-32-KHK",
        name: "32 / Khaki",
        color: "Khaki",
        size: "32",
        currentBuyPrice: 415,
        currentStock: 40,
      },
    ],
  },
  {
    id: "prod-003",
    name: "Premium Hoodie",
    category: "Outerwear",
    variants: [
      {
        id: "var-003-m-grey",
        sku: "HD-M-GREY",
        name: "M / Grey",
        color: "Grey",
        size: "M",
        currentBuyPrice: 650,
        currentStock: 15,
      },
      {
        id: "var-003-l-grey",
        sku: "HD-L-GREY",
        name: "L / Grey",
        color: "Grey",
        size: "L",
        currentBuyPrice: 650,
        currentStock: 10,
      },
      {
        id: "var-003-xl-grey",
        sku: "HD-XL-GREY",
        name: "XL / Grey",
        color: "Grey",
        size: "XL",
        currentBuyPrice: 660,
        currentStock: 8,
      },
    ],
  },
  {
    id: "prod-004",
    name: "Canvas Tote Bag",
    imageUrl: "https://placehold.co/60x60/fef3c7/d97706?text=BG",
    category: "Accessories",
    variants: [
      {
        id: "var-004-nat",
        sku: "TB-NAT",
        name: "Natural",
        color: "Natural",
        currentBuyPrice: 95,
        currentStock: 120,
      },
      {
        id: "var-004-blk",
        sku: "TB-BLK",
        name: "Black",
        color: "Black",
        currentBuyPrice: 95,
        currentStock: 85,
      },
    ],
  },
];

// ─── Purchase Orders ──────────────────────────────────────────────────────────

export const MOCK_ORDERS: PurchaseOrder[] = [
  {
    id: "po-001",
    orderNumber: "PO-2025-0041",
    partyId: "party-001",
    partyName: "Alpha Textiles Pvt Ltd",
    status: "ordered",
    lineItems: [
      {
        id: "li-001-1",
        productId: "prod-001",
        productName: "Classic Cotton T-Shirt",
        variantId: "var-001-m-blk",
        variantName: "M / Black",
        sku: "TS-M-BLK",
        quantity: 100,
        unitCost: 175,
        gstPercent: 5,
      },
      {
        id: "li-001-2",
        productId: "prod-001",
        productName: "Classic Cotton T-Shirt",
        variantId: "var-001-l-blk",
        variantName: "L / Black",
        sku: "TS-L-BLK",
        quantity: 80,
        unitCost: 178,
        gstPercent: 5,
      },
      {
        id: "li-001-3",
        productId: "prod-001",
        productName: "Classic Cotton T-Shirt",
        variantId: "var-001-m-wht",
        variantName: "M / White",
        sku: "TS-M-WHT",
        quantity: 120,
        unitCost: 172,
        gstPercent: 5,
      },
    ],
    totalAmount: 52605,
    createdAt: "2025-04-28T09:15:00Z",
    updatedAt: "2025-04-28T09:15:00Z",
    notes: "Urgent — needed before 5th May",
  },
  {
    id: "po-002",
    orderNumber: "PO-2025-0040",
    partyId: "party-002",
    partyName: "Sunrise Garments",
    status: "partially_received",
    lineItems: [
      {
        id: "li-002-1",
        productId: "prod-002",
        productName: "Slim Fit Chinos",
        variantId: "var-002-32-nvy",
        variantName: "32 / Navy",
        sku: "CH-32-NVY",
        quantity: 50,
        unitCost: 400,
        gstPercent: 12,
      },
      {
        id: "li-002-2",
        productId: "prod-002",
        productName: "Slim Fit Chinos",
        variantId: "var-002-34-nvy",
        variantName: "34 / Navy",
        sku: "CH-34-NVY",
        quantity: 30,
        unitCost: 405,
        gstPercent: 12,
      },
    ],
    totalAmount: 33936,
    createdAt: "2025-04-20T11:30:00Z",
    updatedAt: "2025-04-25T14:00:00Z",
  },
  {
    id: "po-003",
    orderNumber: "PO-2025-0039",
    partyId: "party-003",
    partyName: "Metro Wholesale Suppliers",
    status: "received",
    lineItems: [
      {
        id: "li-003-1",
        productId: "prod-003",
        productName: "Premium Hoodie",
        variantId: "var-003-m-grey",
        variantName: "M / Grey",
        sku: "HD-M-GREY",
        quantity: 40,
        unitCost: 620,
        gstPercent: 12,
      },
      {
        id: "li-003-2",
        productId: "prod-003",
        productName: "Premium Hoodie",
        variantId: "var-003-l-grey",
        variantName: "L / Grey",
        sku: "HD-L-GREY",
        quantity: 35,
        unitCost: 620,
        gstPercent: 12,
      },
      {
        id: "li-003-3",
        productId: "prod-004",
        productName: "Canvas Tote Bag",
        variantId: "var-004-nat",
        variantName: "Natural",
        sku: "TB-NAT",
        quantity: 200,
        unitCost: 88,
        gstPercent: 5,
      },
    ],
    totalAmount: 101948,
    createdAt: "2025-04-10T08:00:00Z",
    updatedAt: "2025-04-18T16:30:00Z",
  },
  {
    id: "po-004",
    orderNumber: "PO-2025-0038",
    partyId: "party-004",
    partyName: "FastTrack Logistics & Trade",
    status: "cancelled",
    lineItems: [
      {
        id: "li-004-1",
        productId: "prod-004",
        productName: "Canvas Tote Bag",
        variantId: "var-004-blk",
        variantName: "Black",
        sku: "TB-BLK",
        quantity: 500,
        unitCost: 85,
        gstPercent: 5,
      },
    ],
    totalAmount: 44625,
    createdAt: "2025-04-05T13:00:00Z",
    updatedAt: "2025-04-08T10:00:00Z",
    notes: "Cancelled due to supplier pricing dispute",
  },
  {
    id: "po-005",
    orderNumber: "PO-2025-0037",
    partyId: "party-001",
    partyName: "Alpha Textiles Pvt Ltd",
    status: "ordered",
    lineItems: [
      {
        id: "li-005-1",
        productId: "prod-002",
        productName: "Slim Fit Chinos",
        variantId: "var-002-30-nvy",
        variantName: "30 / Navy",
        sku: "CH-30-NVY",
        quantity: 75,
        unitCost: 395,
        gstPercent: 12,
        isNewProduct: false,
      },
    ],
    totalAmount: 33124,
    createdAt: "2025-04-28T15:45:00Z",
    updatedAt: "2025-04-28T15:45:00Z",
  },
  {
    id: "po-006",
    orderNumber: "PO-2025-0036",
    partyId: "party-005",
    partyName: "Kumar Brothers",
    status: "received",
    lineItems: [
      {
        id: "li-006-1",
        productId: "prod-001",
        productName: "Classic Cotton T-Shirt",
        variantId: "var-001-s-wht",
        variantName: "S / White",
        sku: "TS-S-WHT",
        quantity: 200,
        unitCost: 168,
        gstPercent: 5,
        isNewProduct: false,
      },
    ],
    totalAmount: 35280,
    createdAt: "2025-03-28T10:00:00Z",
    updatedAt: "2025-04-02T09:30:00Z",
  },
];

export const RECEIVE_METHODS = [
  {
    value: "no_change" as const,
    label: "No Change",
    description: "Keep existing buy prices unchanged",
  },
  {
    value: "weighted_average" as const,
    label: "Weighted Average",
    description: "Blend current stock cost with new order cost",
  },
  {
    value: "override" as const,
    label: "Override",
    description: "Replace buy price with this order's unit cost",
  },
  {
    value: "last_cost" as const,
    label: "Last Cost",
    description: "Use the most recent purchase cost as buy price",
  },
];

export const ORDER_STATUS_CONFIG: Record<
  string,
  { label: string; color: string }
> = {
  ordered: { label: "Ordered", color: "info" },
  partially_received: { label: "Partial", color: "warning" },
  received: { label: "Received", color: "success" },
  cancelled: { label: "Cancelled", color: "default" },
};

export const PRODUCT_CATEGORIES = [
  "Tops",
  "Bottoms",
  "Outerwear",
  "Footwear",
  "Accessories",
  "Innerwear",
  "Activewear",
  "Other",
];
